stages:
- build
- test
build:
  stage: build
  image: kitware/cmake:latest
  before_script:
    - cd semester/
  script:
    - make
test:
  stage: test
  image: kitware/cmake:latest
  before_script: 
    - cd semester/test
    - cmake .
    - make
  script:
    - ./main
